local codeEditorInfos=[[
string subscriberHandle = simROS.subscribe(string topicName, string topicType, func topicCallback, int queueSize=1, map transportHints={})
simROS.shutdownSubscriber(string subscriberHandle)
simROS.subscriberTreatUInt8ArrayAsString(string subscriberHandle)
string publisherHandle = simROS.advertise(string topicName, string topicType, int queueSize=1, bool latch=false)
simROS.shutdownPublisher(string publisherHandle)
simROS.publisherTreatUInt8ArrayAsString(string publisherHandle)
simROS.publish(string publisherHandle, map message)
string serviceClientHandle = simROS.serviceClient(string serviceName, string serviceType)
simROS.shutdownServiceClient(string serviceClientHandle)
simROS.serviceClientTreatUInt8ArrayAsString(string serviceClientHandle)
map result = simROS.call(string serviceClientHandle, map request)
string serviceServerHandle = simROS.advertiseService(string serviceName, string serviceType, func serviceCallback)
simROS.shutdownServiceServer(string serviceServerHandle)
simROS.serviceServerTreatUInt8ArrayAsString(string serviceServerHandle)
simROS.sendTransform(map transform)
simROS.sendTransforms(map transforms)
string subscriberHandle = simROS.imageTransportSubscribe(string topicName, func topicCallback, int queueSize=1)
simROS.imageTransportShutdownSubscriber(string subscriberHandle)
string publisherHandle = simROS.imageTransportAdvertise(string topicName, int queueSize=1)
simROS.imageTransportShutdownPublisher(string publisherHandle)
simROS.imageTransportPublish(string publisherHandle, buffer data, int width, int height, string frame_id)
float time = simROS.getTime(int flag=0)
bool exists, string value = simROS.getParamString(string name, string defaultValue="")
bool exists, int value = simROS.getParamInt(string name, int defaultValue=0)
bool exists, float value = simROS.getParamDouble(string name, float defaultValue=0.0)
bool exists, bool value = simROS.getParamBool(string name, bool defaultValue=false)
simROS.setParamString(string name, string value)
simROS.setParamInt(string name, int value)
simROS.setParamDouble(string name, float value)
simROS.setParamBool(string name, bool value)
bool exists = simROS.hasParam(string name)
simROS.deleteParam(string name)
bool found, string name = simROS.searchParam(string name)
]]

registerCodeEditorInfos("simROS",codeEditorInfos)
