-- simROS lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'
require 'functional'

return function(obj)


    -- accept pure function where callback string is expected:

    obj['subscribe'] = wrap(obj['subscribe'], function(origFunc)
        return function(topicName, topicType, topicCallback, ...)
            return origFunc(topicName, topicType, reify(topicCallback), ...)
        end
    end)

    obj['advertiseService'] = wrap(obj['advertiseService'], function(origFunc)
        return function(serviceName, serviceType, serviceCallback)
            return origFunc(serviceName, serviceType, reify(serviceCallback))
        end
    end)

    obj['imageTransportSubscribe'] = wrap(obj['imageTransportSubscribe'], function(origFunc)
        return function(topicName, topicCallback, ...)
            return origFunc(topicName, reify(topicCallback), ...)
        end
    end)
end
